version: 2.1
orbs:
  git-shallow-clone: tiendanube/git-shallow-clone@2.0.3

jobs:
  build:
    docker:
      - image: cimg/go:1.17.7
    working_directory: /mnt/ramdisk/circle-go-repro
    resource_class: xlarge
    environment:
      GOCACHE: /mnt/ramdisk/go-build-cache
      GOMODCACHE: "/mnt/ramdisk/go-mod-cache"
    steps:
      - git-shallow-clone/checkout:
          path: /mnt/ramdisk/circle-go-repro
      - restore_cache:
          keys:
            - golang-2-{{ checksum "go.sum" }}
            - golang-2-
      - run: go install
      - save_cache:
          paths:
            - "/mnt/ramdisk/go-build-cache"
            - "/mnt/ramdisk/go-mod-cache"
          key: golang-2-{{ checksum "go.sum" }}
      - run: go build && ls go-circle-repro
